import React, { useState, useCallback, useEffect } from 'react';
import ReactDOM from 'react-dom/client';
import { GoogleGenAI, Part } from "@google/genai";

// --- START OF TYPES ---
interface ImageFile {
  id: string;
  file: File;
  preview: string;
}

// --- START OF UTILS ---
async function base64ToFile(base64: string, filename: string, mimeType: string): Promise<File> {
    const res = await fetch(base64);
    const blob = await res.blob();
    return new File([blob], filename, { type: mimeType });
}

// --- START OF GEMINI SERVICE ---
const USER_API_KEY_STORAGE_KEY = 'user_gemini_api_key';

function getGenAIClient(): GoogleGenAI {
  const userApiKey = localStorage.getItem(USER_API_KEY_STORAGE_KEY);
  const apiKey = userApiKey || process.env.API_KEY;

  if (!apiKey) {
    throw new Error("API_KEY is not set. Please provide it in the settings or as an environment variable.");
  }

  return new GoogleGenAI({ apiKey });
}

function isUsingUserApiKey(): boolean {
  return localStorage.getItem(USER_API_KEY_STORAGE_KEY) !== null;
}

async function fileToGenerativePart(file: File): Promise<Part> {
  const base64EncodedDataPromise = new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
    reader.readAsDataURL(file);
  });
  return {
    inlineData: {
      data: await base64EncodedDataPromise,
      mimeType: file.type,
    },
  };
}

async function generateDescriptionForImage(image: File): Promise<string> {
    const ai = getGenAIClient();
    const imagePart = await fileToGenerativePart(image);
    const textPart = {
        text: "صف صورة المنتج هذه بطريقة تكون بمثابة وصف ممتاز لمولد صور الذكاء الاصطناعي لإنشاء لقطة منتج احترافية. كن مبدعًا واقترح خلفية وإضاءة مثيرة للاهتمام. على سبيل المثال: 'صورة فوتوغرافية احترافية للمنتج على سطح من خشب البلوط الداكن، مع إضاءة جانبية ناعمة ودافئة تخلق توهجًا لطيفًا على قوامه.'"
    };
    
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: { parts: [imagePart, textPart] }
    });

    return response.text;
}

async function generateProductImage(images: File[], prompt: string): Promise<string> {
    const ai = getGenAIClient();
    const imageParts = await Promise.all(images.map(fileToGenerativePart));
    const textPart = { text: prompt };

    const contents = {
        parts: [...imageParts, textPart]
    };
    
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents,
    });

    if (!response.candidates || response.candidates.length === 0 || !response.candidates[0].content || !response.candidates[0].content.parts) {
        throw new Error("Invalid response from API. The prompt may have been blocked or the API failed to generate an image.");
    }

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }

    throw new Error("No image was generated by the API.");
}

async function refineImage(image: File, prompt: string): Promise<string> {
    const ai = getGenAIClient();
    const imagePart = await fileToGenerativePart(image);
    const textPart = { text: prompt };

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts: [imagePart, textPart] },
    });

    if (!response.candidates || response.candidates.length === 0 || !response.candidates[0].content || !response.candidates[0].content.parts) {
        throw new Error("Invalid response from API. The prompt may have been blocked or the API failed to refine the image.");
    }

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }
    
    throw new Error("Image refinement failed.");
}


// --- START OF ICONS ---
type IconProps = {
  className?: string;
};

const UploadIcon: React.FC<IconProps> = ({ className }) => (
  <svg className={className} aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 16">
    <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 13h3a3 3 0 0 0 0-6h-.025A5.56 5.56 0 0 0 16 6.5 5.5 5.5 0 0 0 5.207 5.021C5.137 5.017 5.071 5 5 5a4 4 0 0 0 0 8h2.167M10 15V6m0 0L8 8m2-2 2 2" />
  </svg>
);

const TrashIcon: React.FC<IconProps> = ({ className }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
  </svg>
);

const SparklesIcon: React.FC<IconProps> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" className={className} viewBox="0 0 20 20" fill="currentColor">
        <path fillRule="evenodd" d="M5 2a1 1 0 00-1 1v1.586l-2.707 2.707a1 1 0 000 1.414l2.707 2.707V13a1 1 0 001 1h1.586l2.707 2.707a1 1 0 001.414 0l2.707-2.707H15a1 1 0 001-1v-1.586l2.707-2.707a1 1 0 000-1.414L16.586 5.586V4a1 1 0 00-1-1h-1.586l-2.707-2.707a1 1 0 00-1.414 0L7.586 2H6a1 1 0 00-1-1zM10 12a2 2 0 100-4 2 2 0 000 4z" clipRule="evenodd" />
    </svg>
);

const PhotoIcon: React.FC<IconProps> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="m2.25 15.75 5.159-5.159a2.25 2.25 0 0 1 3.182 0l5.159 5.159m-1.5-1.5 1.409-1.409a2.25 2.25 0 0 1 3.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 0 0 1.5-1.5V6a1.5 1.5 0 0 0-1.5-1.5H3.75A1.5 1.5 0 0 0 2.25 6v12a1.5 1.5 0 0 0 1.5 1.5Zm10.5-11.25h.008v.008h-.008V8.25Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
    </svg>
);

const CutIcon: React.FC<IconProps> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M7.843 1.802a.75.75 0 0 1 1.06 0l2.25 2.25a.75.75 0 0 1 0 1.06l-2.25 2.25a.75.75 0 0 1-1.06 0l-2.25-2.25a.75.75 0 0 1 0-1.06l2.25-2.25Zm-2.625 2.625 2.625-2.625m0 5.25-2.625-2.625m2.625 2.625-2.625 2.625m0-5.25 2.625 2.625M17.657 7.843a.75.75 0 0 1 1.06 0l2.25 2.25a.75.75 0 0 1 0 1.06l-2.25 2.25a.75.75 0 0 1-1.06 0l-2.25-2.25a.75.75 0 0 1 0-1.06l2.25-2.25Zm-2.625 2.625 2.625-2.625m0 5.25-2.625-2.625m2.625 2.625-2.625 2.625m0-5.25 2.625 2.625M3.101 18.198a2.25 2.25 0 0 0 3.182 0l1.238-1.238 2.33-2.33a.75.75 0 0 1 1.061 0l2.33 2.33 3.469-3.469a2.25 2.25 0 0 0-3.182-3.182l-3.47 3.47-2.33-2.33a.75.75 0 0 1 0-1.061l2.33-2.33 1.238-1.238a2.25 2.25 0 0 0 0-3.182L9.48 3.101a2.25 2.25 0 0 0-3.182 0L3.1 9.299a2.25 2.25 0 0 0 0 3.182l3.198 3.198-3.198 3.198Z" />
    </svg>
);

const WandIcon: React.FC<IconProps> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.53 16.122a3 3 0 0 0-5.78 1.128 2.25 2.25 0 0 1-2.475 2.118 2.25 2.25 0 0 1-2.475-2.118c0-.493.212-.962.57-1.32a3 3 0 0 0 4.38-1.322a3 3 0 0 0 .577-1.318 2.25 2.25 0 0 1 2.34-1.884 2.25 2.25 0 0 1 2.34 1.884 3 3 0 0 0 .577 1.318a3 3 0 0 0 4.38 1.322c.358.358.57.827.57 1.32a2.25 2.25 0 0 1-2.475 2.118 2.25 2.25 0 0 1-2.475-2.118a3 3 0 0 0-5.78-1.128Zm0 0a3 3 0 0 0-5.78 1.128m5.78-1.128a3 3 0 0 1 5.78 1.128m-5.78-1.128v-5.172a2.25 2.25 0 0 1 .166-2.983l.53-.53a2.25 2.25 0 0 0 .166-2.983l-.53-.53a2.25 2.25 0 0 0-2.982-.166l-.53.53a2.25 2.25 0 0 0-2.983.166l-.53-.53a2.25 2.25 0 0 0-2.982.166l.53.53a2.25 2.25 0 0 0 .166 2.983l.53.53a2.25 2.25 0 0 1 .166 2.983v5.172" />
    </svg>
);

const SparklesIconV2: React.FC<IconProps> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456Z" />
    </svg>
);

const DownloadIcon: React.FC<IconProps> = ({ className }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3" />
  </svg>
);

const DiamondIcon: React.FC<IconProps> = ({ className }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M11.48 3.499a.562.562 0 0 1 1.04 0l2.125 5.111a.563.563 0 0 0 .475.324h5.364a.562.562 0 0 1 .321.988l-4.204 3.192a.563.563 0 0 0-.182.557l1.528 4.718a.562.562 0 0 1-.82.623l-3.876-2.801a.563.563 0 0 0-.68 0L6.22 21.01a.562.562 0 0 1-.82-.623l1.528-4.718a.563.563 0 0 0-.182-.557l-4.204-3.192a.563.563 0 0 1 .321-.988h5.364a.563.563 0 0 0 .475-.324L11.48 3.5Z" />
  </svg>
);

const GearIcon: React.FC<IconProps> = ({ className }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M9.594 3.94c.09-.542.56-1.007 1.11-.111l.281.281c.099.099.231.157.372.157h.423c.394 0 .755.23.91.592l.147.345a.65.65 0 0 0 1.012.353l.383-.245a.652.652 0 0 1 .82.26l.208.364a.652.652 0 0 1-.027.81l-.282.282a.65.65 0 0 0 0 .916l.282.282a.652.652 0 0 1 .027.81l-.208.364a.652.652 0 0 1-.82.26l-.383-.245a.65.65 0 0 0-1.012.353l-.147.345a.65.65 0 0 1-.91.592h-.423c-.141 0-.273.058-.372.157l-.281.281a.652.652 0 0 1-1.11-.111l-.091-.542a.651.651 0 0 0-.52-1.026l-.423-.112a.65.65 0 0 1-.418-.68l.092-.542a.65.65 0 0 0 .04-1.026l-.423-.112a.651.651 0 0 1-.418-.68l.092-.542a.651.651 0 0 0 .52-1.026l.423-.112a.65.65 0 0 1 .418-.68l-.092-.542a.65.65 0 0 0-.04-1.026l.423-.112a.651.651 0 0 1 .418-.68l-.091-.542Z" />
    <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
  </svg>
);

const EyeIcon: React.FC<IconProps> = ({ className }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.644l7.657-7.657a1.012 1.012 0 0 1 1.431 0l7.657 7.657a1.012 1.012 0 0 1 0 .644l-7.657 7.657a1.012 1.012 0 0 1-1.431 0l-7.657-7.657Z" />
    <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
  </svg>
);

const EyeSlashIcon: React.FC<IconProps> = ({ className }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.451 10.451 0 0 1 12 4.5c4.756 0 8.773 3.162 10.065 7.498a10.522 10.522 0 0 1-4.293 5.774M6.228 6.228 3 3m3.228 3.228 3.65 3.65m7.894 7.894L21 21m-3.228-3.228-3.65-3.65m0 0a3 3 0 1 0-4.243-4.243m4.243 4.243-4.243-4.243" />
  </svg>
);

const CloseIcon: React.FC<IconProps> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" />
    </svg>
);

const UndoIcon: React.FC<IconProps> = ({ className }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3" />
  </svg>
);

const RedoIcon: React.FC<IconProps> = ({ className }) => (
  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
    <path strokeLinecap="round" strokeLinejoin="round" d="m15 15 6-6m0 0-6-6m6 6H9a6 6 0 0 0 0 12h3" />
  </svg>
);

const CreateVariationIcon: React.FC<IconProps> = ({ className }) => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className={className}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
    </svg>
);


// --- START OF COMPONENTS ---

// Footer.tsx
const Footer: React.FC = () => {
  return (
    <footer className="py-4 mt-8">
      <div className="container mx-auto text-center text-gray-500 text-sm">
        <p>&copy; {new Date().getFullYear()} استوديو تصوير المنتجات بالذكاء الاصطناعي. جميع الحقوق محفوظة.</p>
      </div>
    </footer>
  );
};

// Header.tsx
interface HeaderProps {
  onSettingsClick: () => void;
}
const Header: React.FC<HeaderProps> = ({ onSettingsClick }) => {
  return (
    <header className="py-4 md:py-6 relative">
      <div className="container mx-auto text-center">
        <h1 className="text-3xl md:text-5xl font-bold bg-gradient-to-r from-indigo-400 to-cyan-400 text-transparent bg-clip-text">
          استوديو تصوير المنتجات بالذكاء الاصطناعي
        </h1>
        <p className="text-gray-400 mt-2 text-md md:text-lg">
          حوّل صور منتجاتك إلى روائع احترافية.
        </p>
      </div>
      <button 
        onClick={onSettingsClick}
        className="absolute top-1/2 -translate-y-1/2 right-4 md:right-8 p-2 text-gray-400 hover:text-white hover:bg-gray-700 rounded-full transition-all duration-200 transform hover:scale-110"
        aria-label="الإعدادات"
        title="الإعدادات"
      >
        <GearIcon className="w-6 h-6" />
      </button>
    </header>
  );
};

// ImageUploader.tsx
interface ImageUploaderProps {
  onUpload: (files: ImageFile[]) => void;
  maxFiles: number;
  imageFiles: ImageFile[];
  onRefine: (imageId: string, refinementType: 'remove-background' | 'enhance' | 'cleanup') => void;
  refinementState: { [key: string]: boolean };
}
const ImageUploader: React.FC<ImageUploaderProps> = ({ 
  onUpload, 
  maxFiles,
  imageFiles, 
  onRefine,
  refinementState
}) => {
  const [isDragging, setIsDragging] = useState(false);

  const handleFiles = useCallback((files: FileList | null) => {
    if (!files) return;

    const newFiles = Array.from(files)
      .filter(file => file.type.startsWith('image/'))
      .slice(0, maxFiles - imageFiles.length);
      
    const newImageFiles: ImageFile[] = newFiles.map(file => ({
      id: `${file.name}-${Date.now()}`,
      file,
      preview: URL.createObjectURL(file)
    }));
    
    const updatedFiles = [...imageFiles, ...newImageFiles];
    onUpload(updatedFiles);
  }, [imageFiles, maxFiles, onUpload]);

  const handleDragEnter = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  };

  const handleDragLeave = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
  };
  
  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
    handleFiles(e.dataTransfer.files);
  };
  
  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    handleFiles(e.target.files);
  };
  
  const removeImage = (id: string) => {
    const imageToRemove = imageFiles.find(img => img.id === id);
    if (imageToRemove) {
      URL.revokeObjectURL(imageToRemove.preview);
    }
    const updatedFiles = imageFiles.filter(img => img.id !== id);
    onUpload(updatedFiles);
  };

  return (
    <div>
      <label className="block text-sm font-medium text-gray-300 mb-2">١. رفع صور المنتج (حتى {maxFiles} صور)</label>
      <div 
        onDragEnter={handleDragEnter}
        onDragLeave={handleDragLeave}
        onDragOver={handleDragOver}
        onDrop={handleDrop}
        className={`relative flex flex-col items-center justify-center w-full h-48 border-2 border-dashed rounded-lg cursor-pointer transition-colors duration-300 ${isDragging ? 'border-indigo-500 bg-gray-700/50' : 'border-gray-600 hover:border-gray-500 bg-gray-800'}`}
      >
        <div className="flex flex-col items-center justify-center pt-5 pb-6">
          <UploadIcon className="w-10 h-10 mb-3 text-gray-400" />
          <p className="mb-2 text-sm text-gray-400"><span className="font-semibold">انقر للرفع</span> أو اسحب وأفلت</p>
          <p className="text-xs text-gray-500">PNG, JPG, or WEBP</p>
        </div>
        <input id="dropzone-file" type="file" className="absolute w-full h-full opacity-0 cursor-pointer" multiple accept="image/*" onChange={handleFileChange} disabled={imageFiles.length >= maxFiles} />
      </div>

      {imageFiles.length > 0 && (
        <div className="mt-4 grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 gap-4">
          {imageFiles.map(imageFile => {
            const isRefining = refinementState[imageFile.id];
            return (
              <div key={imageFile.id} className="relative group">
                <img src={imageFile.preview} alt="preview" className={`w-full h-24 object-cover rounded-lg transition-all duration-200 group-hover:scale-105 ${isRefining ? 'opacity-30' : ''}`} />
                {isRefining && (
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="w-6 h-6 border-2 border-t-transparent border-white rounded-full animate-spin"></div>
                  </div>
                )}
                {!isRefining && (
                  <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-1.5">
                    <button onClick={() => onRefine(imageFile.id, 'remove-background')} title="إزالة الخلفية" className="p-1.5 bg-gray-700/80 rounded-full text-white hover:bg-indigo-600 transition-all transform hover:scale-110"><CutIcon className="w-4 h-4" /></button>
                    <button onClick={() => onRefine(imageFile.id, 'enhance')} title="تحسين الإضاءة والألوان" className="p-1.5 bg-gray-700/80 rounded-full text-white hover:bg-indigo-600 transition-all transform hover:scale-110"><WandIcon className="w-4 h-4" /></button>
                    <button onClick={() => onRefine(imageFile.id, 'cleanup')} title="إزالة الشوائب" className="p-1.5 bg-gray-700/80 rounded-full text-white hover:bg-indigo-600 transition-all transform hover:scale-110"><SparklesIconV2 className="w-4 h-4" /></button>
                  </div>
                )}
                <button 
                  onClick={() => removeImage(imageFile.id)}
                  className="absolute top-1 right-1 p-1 bg-red-600/70 rounded-full text-white opacity-0 group-hover:opacity-100 transition-opacity disabled:opacity-50"
                  disabled={isRefining}
                >
                  <TrashIcon className="w-4 h-4" />
                </button>
              </div>
            )
          })}
        </div>
      )}
    </div>
  );
};

// PostGenerationEditor.tsx
interface PostGenerationEditorProps {
  onEdit: (prompt: string) => void;
  disabled: boolean;
}
const cropOptions = [
  { name: 'مربع 1:1', prompt: 'Crop the image to a 1:1 square aspect ratio, keeping the main subject perfectly centered.' },
  { name: 'عريض 16:9', prompt: 'Crop the image to a 16:9 widescreen aspect ratio, focusing on the most visually interesting part of the scene.' },
  { name: 'طولي 4:5', prompt: 'Crop the image to a 4:5 portrait aspect ratio, ideal for social media posts.' },
];
const filterOptions = [
  { name: 'فينتاج', prompt: 'Apply a warm, vintage film filter to this image, with subtle grain and slightly faded colors.' },
  { name: 'أبيض وأسود', prompt: 'Convert this image to a high-contrast, dramatic black and white photograph.' },
  { name: 'ألوان زاهية', prompt: 'Enhance the vibrancy and saturation of the colors in this image to make it pop.' },
  { name: 'تركيز ناعم', prompt: 'Apply a soft focus effect or a gentle blur to the background, making the main subject stand out more.' },
];
const EditButton: React.FC<{onClick: () => void, disabled: boolean, children: React.ReactNode}> = ({ onClick, disabled, children }) => (
    <button
        onClick={onClick}
        disabled={disabled}
        className="px-3 py-1.5 text-xs font-semibold text-white bg-black/40 backdrop-blur-sm border border-white/20 rounded-md hover:bg-white/20 disabled:opacity-50 disabled:cursor-not-allowed transition-all transform hover:scale-105"
    >
        {children}
    </button>
);
const PostGenerationEditor: React.FC<PostGenerationEditorProps> = ({ onEdit, disabled }) => {
  return (
    <div className="w-full max-w-md p-3 bg-black/30 backdrop-blur-md rounded-lg border border-white/10">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <h4 className="text-xs font-bold text-gray-300 mb-2 text-center sm:text-right">قص الصورة</h4>
          <div className="flex flex-wrap gap-2 justify-center sm:justify-start">
            {cropOptions.map(opt => (
              <EditButton key={opt.name} onClick={() => onEdit(opt.prompt)} disabled={disabled}>
                {opt.name}
              </EditButton>
            ))}
          </div>
        </div>
        <div>
          <h4 className="text-xs font-bold text-gray-300 mb-2 text-center sm:text-right">فلاتر فنية</h4>
          <div className="flex flex-wrap gap-2 justify-center sm:justify-start">
            {filterOptions.map(opt => (
              <EditButton key={opt.name} onClick={() => onEdit(opt.prompt)} disabled={disabled}>
                {opt.name}
              </EditButton>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

// PromptControls.tsx
interface PromptControlsProps {
  prompt: string;
  setPrompt: (value: string) => void;
  onGenerateDescription: () => void;
  isGeneratingDescription: boolean;
  isImageUploaded: boolean;
}
const PromptControls: React.FC<PromptControlsProps> = ({
  prompt,
  setPrompt,
  onGenerateDescription,
  isGeneratingDescription,
  isImageUploaded,
}) => {
  return (
    <div>
      <label htmlFor="prompt" className="block text-sm font-medium text-gray-300 mb-2">٢. صف المشهد المطلوب</label>
      <div className="relative">
        <textarea
          id="prompt"
          rows={4}
          className="block w-full text-sm rounded-lg border bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500 p-2.5 ps-3 pe-28"
          placeholder="مثال: لقطة احترافية على سطح من الرخام الأبيض مع إضاءة صباحية طبيعية وناعمة..."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
        />
        <button
          onClick={onGenerateDescription}
          disabled={!isImageUploaded || isGeneratingDescription}
          className="absolute bottom-2.5 left-2.5 text-white bg-gray-600 hover:bg-gray-500 disabled:bg-gray-700 disabled:cursor-not-allowed focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-xs px-3 py-2 flex items-center gap-1 transition-transform transform hover:scale-105"
        >
          {isGeneratingDescription ? (
             <div className="w-4 h-4 border-2 border-t-transparent border-white rounded-full animate-spin"></div>
          ) : (
            <SparklesIcon className="w-4 h-4" />
          )}
          <span>مساعدة AI</span>
        </button>
      </div>
    </div>
  );
};

// ResultDisplay.tsx
interface ResultDisplayProps {
  isLoading: boolean;
  generatedImage: string | null;
  onGenerateHQ: () => void;
  isEditing: boolean;
  onEditImage: (prompt: string) => void;
  onUndo: () => void;
  onRedo: () => void;
  canUndo: boolean;
  canRedo: boolean;
  isGeneratingVariations: boolean;
  variationImages: string[];
  onGenerateVariations: () => void;
  onSelectVariation: (url: string) => void;
}
const Spinner: React.FC = () => (
  <div className="flex flex-col items-center justify-center gap-4">
    <div className="w-16 h-16 border-4 border-dashed border-indigo-400 rounded-full animate-spin"></div>
    <p className="text-lg text-gray-300">جاري إنشاء تحفتك الفنية...</p>
    <p className="text-sm text-gray-500">قد يستغرق هذا بعض الوقت.</p>
  </div>
);
const Placeholder: React.FC = () => (
    <div className="flex flex-col items-center justify-center h-full text-center text-gray-500 p-4">
        <PhotoIcon className="w-24 h-24 mb-4" />
        <h3 className="text-xl font-semibold text-gray-400">ستظهر صورتك الاحترافية هنا</h3>
        <p className="mt-2 max-w-sm">ارفع صور منتجك، صف المشهد الذي تتخيله، ثم انقر على زر الإنشاء.</p>
    </div>
);
const ResultDisplay: React.FC<ResultDisplayProps> = ({ 
    isLoading, 
    generatedImage, 
    onGenerateHQ, 
    isEditing, 
    onEditImage,
    onUndo,
    onRedo,
    canUndo,
    canRedo,
    isGeneratingVariations,
    variationImages,
    onGenerateVariations,
    onSelectVariation,
}) => {
  const [imageLoaded, setImageLoaded] = useState(false);

  useEffect(() => {
    if (generatedImage && !isLoading) {
      const timer = setTimeout(() => setImageLoaded(true), 50);
      return () => clearTimeout(timer);
    } else {
      setImageLoaded(false);
    }
  }, [generatedImage, isLoading]);

  const handleDownload = () => {
    if (!generatedImage) return;
    const link = document.createElement('a');
    link.href = generatedImage;
    link.download = `product-image-${Date.now()}.jpeg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };
  
  return (
    <div className="relative lg:sticky lg:top-8 flex items-center justify-center p-6 bg-gray-800/50 rounded-2xl aspect-square w-full border border-gray-700 min-h-[300px] lg:min-h-0">
      {isLoading ? (
        <Spinner />
      ) : generatedImage ? (
        <>
          <img 
            src={generatedImage} 
            alt="Generated product" 
            className={`w-full h-full object-contain rounded-lg transition-all duration-500 ease-in-out ${imageLoaded ? 'opacity-100 scale-100' : 'opacity-0 scale-95'}`} 
          />
           {(isEditing || isGeneratingVariations) && (
             <div className="absolute inset-0 bg-black/60 flex items-center justify-center z-10 rounded-2xl">
                <div className="flex flex-col items-center justify-center gap-4">
                    <div className="w-12 h-12 border-4 border-dashed border-cyan-400 rounded-full animate-spin"></div>
                    <p className="text-lg text-gray-200">
                        {isEditing ? 'جاري تطبيق التعديلات...' : 'جاري إنشاء التنويعات...'}
                    </p>
                </div>
            </div>
          )}
          <div className="absolute bottom-4 left-4 right-4 flex flex-col items-center gap-3">
             <div className="flex justify-center items-center gap-2 flex-wrap">
                <button
                    onClick={onUndo}
                    disabled={!canUndo || isEditing || isLoading || isGeneratingVariations}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-black/50 backdrop-blur-sm border border-white/20 rounded-lg hover:bg-white/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-105"
                    title="تراجع"
                >
                    <UndoIcon className="w-4 h-4" />
                </button>
                <button
                    onClick={onRedo}
                    disabled={!canRedo || isEditing || isLoading || isGeneratingVariations}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-black/50 backdrop-blur-sm border border-white/20 rounded-lg hover:bg-white/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-105"
                    title="إعادة"
                >
                    <RedoIcon className="w-4 h-4" />
                </button>
                <button
                onClick={handleDownload}
                disabled={isEditing || isLoading || isGeneratingVariations}
                className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-black/50 backdrop-blur-sm border border-white/20 rounded-lg hover:bg-white/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-105"
                >
                <DownloadIcon className="w-4 h-4" />
                <span>حفظ</span>
                </button>
                <button
                    onClick={onGenerateVariations}
                    disabled={isEditing || isLoading || isGeneratingVariations}
                    className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-black/50 backdrop-blur-sm border border-white/20 rounded-lg hover:bg-white/20 transition-all disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-105"
                >
                    <CreateVariationIcon className="w-4 h-4" />
                    <span>تنويعات</span>
                </button>
                <button
                onClick={onGenerateHQ}
                disabled={isEditing || isLoading || isGeneratingVariations}
                className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-indigo-600/80 backdrop-blur-sm border border-indigo-500/50 rounded-lg hover:bg-indigo-500 transition-all disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-105"
                >
                <DiamondIcon className="w-4 h-4" />
                <span>جودة فائقة</span>
                </button>
             </div>
             {variationImages.length > 0 && !isGeneratingVariations && (
                <div className="w-full max-w-md p-2 bg-black/30 backdrop-blur-md rounded-lg border border-white/10">
                    <h4 className="text-xs font-bold text-gray-300 mb-2 text-center">اختر تنويعة</h4>
                    <div className="grid grid-cols-3 gap-2">
                        {variationImages.map((imgSrc, index) => (
                            <button key={index} onClick={() => onSelectVariation(imgSrc)} className="block rounded-md overflow-hidden border-2 border-transparent hover:border-indigo-500 focus:border-indigo-500 transition-all transform hover:scale-105 focus:outline-none">
                                <img src={imgSrc} alt={`Variation ${index + 1}`} className="w-full h-20 object-cover" />
                            </button>
                        ))}
                    </div>
                </div>
            )}
            <PostGenerationEditor onEdit={onEditImage} disabled={isEditing || isLoading || isGeneratingVariations} />
          </div>
        </>
      ) : (
        <Placeholder />
      )}
    </div>
  );
};

// SettingsModal.tsx
interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
}
const SettingsModal: React.FC<SettingsModalProps> = ({ isOpen, onClose }) => {
  const [apiKey, setApiKey] = useState('');
  const [isKeyVisible, setIsKeyVisible] = useState(false);
  const [saved, setSaved] = useState(false);
  const [showContent, setShowContent] = useState(false);

  useEffect(() => {
    if (isOpen) {
      const storedKey = localStorage.getItem(USER_API_KEY_STORAGE_KEY);
      setApiKey(storedKey || '');
      setSaved(false);
      const timer = setTimeout(() => setShowContent(true), 50);
      return () => clearTimeout(timer);
    } else {
      setShowContent(false);
    }
  }, [isOpen]);

  if (!isOpen) {
    return null;
  }

  const handleSave = () => {
    if (apiKey.trim()) {
      localStorage.setItem(USER_API_KEY_STORAGE_KEY, apiKey.trim());
    } else {
      localStorage.removeItem(USER_API_KEY_STORAGE_KEY);
    }
    setSaved(true);
    setTimeout(() => {
        onClose();
    }, 1000);
  };

  const handleRemove = () => {
    localStorage.removeItem(USER_API_KEY_STORAGE_KEY);
    setApiKey('');
  };

  return (
    <div 
      className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 transition-opacity duration-300"
      onClick={onClose}
    >
      <div 
        className={`bg-gray-800 rounded-2xl shadow-2xl p-6 md:p-8 border border-gray-700 w-full max-w-lg m-4 transform transition-all duration-300 ease-out ${showContent ? 'opacity-100 scale-100' : 'opacity-0 scale-95'}`}
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex justify-between items-center mb-4">
          <h2 className="text-xl font-bold text-white">الإعدادات</h2>
          <button onClick={onClose} className="p-1 text-gray-400 hover:text-white">
            <CloseIcon className="w-6 h-6" />
          </button>
        </div>
        
        <div className="space-y-4">
          <div>
            <label htmlFor="api-key" className="block text-sm font-medium text-gray-300 mb-2">
              مفتاح Gemini API الخاص بك
            </label>
            <div className="relative">
                <input
                    id="api-key"
                    type={isKeyVisible ? 'text' : 'password'}
                    className="block w-full text-sm rounded-lg border bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500 p-2.5 ps-3 pe-10"
                    placeholder="أدخل مفتاحك هنا..."
                    value={apiKey}
                    onChange={(e) => setApiKey(e.target.value)}
                />
                <button
                    onClick={() => setIsKeyVisible(!isKeyVisible)}
                    className="absolute inset-y-0 end-0 flex items-center pe-3 text-gray-400 hover:text-white"
                    aria-label={isKeyVisible ? "إخفاء المفتاح" : "إظهار المفتاح"}
                >
                    {isKeyVisible ? <EyeSlashIcon className="w-5 h-5" /> : <EyeIcon className="w-5 h-5" />}
                </button>
            </div>
            <p className="text-xs text-gray-500 mt-2">
                سيتم تخزين مفتاحك بأمان في متصفحك. 
                <a href="https://aistudio.google.com/app/apikey" target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:underline">
                    {' '}احصل على مفتاح API من Google AI Studio.
                </a>
            </p>
          </div>
          
          <div className="flex items-center justify-between gap-4">
            <button
                onClick={handleRemove}
                disabled={!apiKey}
                className="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-gray-300 bg-gray-700/50 backdrop-blur-sm border border-gray-600 rounded-lg hover:bg-red-900/50 hover:border-red-700 hover:text-red-300 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                >
                <TrashIcon className="w-4 h-4" />
                <span>إزالة المفتاح</span>
            </button>
            <button
                onClick={handleSave}
                className={`px-6 py-2 text-sm font-semibold rounded-lg transition-colors ${saved ? 'bg-green-600' : 'bg-indigo-600 hover:bg-indigo-700'}`}
            >
                {saved ? 'تم الحفظ!' : 'حفظ'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};


// StylePresets.tsx
interface StylePresetsProps {
  onSelect: (prompt: string) => void;
}
const styles = [
  { name: 'سينمائي', prompt: 'لقطة سينمائية، إضاءة درامية، تباين عالٍ' },
  { name: 'بسيط', prompt: 'أسلوب بسيط ونظيف، خلفية أحادية اللون' },
  { name: 'حيوي', prompt: 'ألوان زاهية ومفعمة بالحيوية، إضاءة ساطعة' },
  { name: 'غامض', prompt: 'أجواء غامضة، ظلال عميقة، إضاءة خافتة' },
  { name: 'فاخر', prompt: 'مظهر فاخر وأنيق، تفاصيل ذهبية' },
];
const StylePresets: React.FC<StylePresetsProps> = ({ onSelect }) => {
  return (
    <div>
      <label className="block text-sm font-medium text-gray-300 mb-2">٣. اختر نمطًا (اختياري)</label>
      <div className="flex flex-wrap gap-2">
        {styles.map((style) => (
          <button
            key={style.name}
            onClick={() => onSelect(style.prompt)}
            className="text-white bg-gray-600 hover:bg-gray-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-xs px-3 py-1.5 transition-all duration-200 transform hover:scale-105"
          >
            {style.name}
          </button>
        ))}
      </div>
    </div>
  );
};

// BackgroundGallery.tsx
interface BackgroundGalleryProps {
  onSelect: (prompt: string) => void;
}
const backgrounds = [
  { name: 'سطح رخامي', prompt: 'المنتج على سطح من الرخام الأبيض الفاخر' },
  { name: 'طاولة خشبية', prompt: 'المنتج على طاولة خشبية ريفية' },
  { name: 'خلفية متدرجة', prompt: 'المنتج مع خلفية متدرجة بألوان الباستيل' },
  { name: 'منصة حجرية', prompt: 'المنتج معروض على منصة حجرية طبيعية' },
  { name: 'في الطبيعة', prompt: 'المنتج في الهواء الطلق مع خلفية طبيعية ضبابية' },
];
const BackgroundGallery: React.FC<BackgroundGalleryProps> = ({ onSelect }) => {
  return (
    <div>
      <label className="block text-sm font-medium text-gray-300 mb-2">٤. اختر خلفية (اختياري)</label>
      <div className="flex flex-wrap gap-2">
        {backgrounds.map((bg) => (
          <button
            key={bg.name}
            onClick={() => onSelect(bg.prompt)}
            className="text-white bg-gray-600 hover:bg-gray-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-xs px-3 py-1.5 transition-all duration-200 transform hover:scale-105"
          >
            {bg.name}
          </button>
        ))}
      </div>
    </div>
  );
};


// --- NEW LOGIN COMPONENT ---
const LoginComponent: React.FC<{ onLoginSuccess: () => void }> = ({ onLoginSuccess }) => {
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState('');

    const handleLogin = (e: React.FormEvent) => {
        e.preventDefault();
        if (username === 'Admin' && password === 'Admin') {
            setError('');
            onLoginSuccess();
        } else {
            setError('اسم المستخدم أو كلمة المرور غير صحيحة.');
        }
    };

    return (
        <div className="min-h-screen bg-gray-900 text-gray-100 flex flex-col justify-center items-center p-4">
            <div className="w-full max-w-sm">
                <div className="text-center mb-8">
                    <h1 className="text-3xl md:text-4xl font-bold bg-gradient-to-r from-indigo-400 to-cyan-400 text-transparent bg-clip-text">
                        تسجيل الدخول
                    </h1>
                    <p className="text-gray-400 mt-2">
                        للوصول إلى استوديو تصوير المنتجات
                    </p>
                </div>
                <div className="bg-gray-800/50 p-8 rounded-2xl shadow-lg border border-gray-700">
                    <form onSubmit={handleLogin} className="space-y-6">
                        <div>
                            <label
                                htmlFor="username"
                                className="block text-sm font-medium text-gray-300 mb-2"
                            >
                                اسم المستخدم
                            </label>
                            <input
                                id="username"
                                type="text"
                                value={username}
                                onChange={(e) => setUsername(e.target.value)}
                                required
                                className="block w-full text-sm rounded-lg border bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500 p-2.5"
                                placeholder="أدخل اسم المستخدم"
                            />
                        </div>
                        <div>
                            <label
                                htmlFor="password"
                                className="block text-sm font-medium text-gray-300 mb-2"
                            >
                                كلمة المرور
                            </label>
                            <input
                                id="password"
                                type="password"
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                                required
                                className="block w-full text-sm rounded-lg border bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500 p-2.5"
                                placeholder="••••••••"
                            />
                        </div>
                        {error && (
                            <div className="bg-red-900/50 border border-red-700 text-red-300 px-4 py-3 rounded-lg text-sm">
                                {error}
                            </div>
                        )}
                        <button
                            type="submit"
                            className="w-full bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-900/50 text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 ease-in-out shadow-indigo-500/30 shadow-md transform hover:scale-105"
                        >
                            دخول
                        </button>
                    </form>
                </div>
            </div>
        </div>
    );
};

// --- MAIN APP COMPONENT ---
function App(): React.ReactElement {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [appVisible, setAppVisible] = useState(false);
  const [imageFiles, setImageFiles] = useState<ImageFile[]>([]);
  const [prompt, setPrompt] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [isGeneratingDescription, setIsGeneratingDescription] = useState<boolean>(false);
  const [refinementState, setRefinementState] = useState<{ [key: string]: boolean }>({});
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [editHistory, setEditHistory] = useState<string[]>([]);
  const [historyIndex, setHistoryIndex] = useState<number>(-1);
  const [isEditing, setIsEditing] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [isSettingsOpen, setIsSettingsOpen] = useState<boolean>(false);
  const [apiKeyStatus, setApiKeyStatus] = useState(isUsingUserApiKey());
  const [variationImages, setVariationImages] = useState<string[]>([]);
  const [isGeneratingVariations, setIsGeneratingVariations] = useState<boolean>(false);

  useEffect(() => {
    if(isAuthenticated) {
        const timer = setTimeout(() => setAppVisible(true), 100);
        return () => clearTimeout(timer);
    }
  }, [isAuthenticated]);

  const handleLoginSuccess = () => {
    setIsAuthenticated(true);
  };

  const handleSettingsClose = () => {
    setIsSettingsOpen(false);
    setApiKeyStatus(isUsingUserApiKey());
  };

  const handleImageUpload = (newFiles: ImageFile[]) => {
    setImageFiles(newFiles);
  };
  
  const handleRefineImage = useCallback(async (
    imageId: string, 
    refinementType: 'remove-background' | 'enhance' | 'cleanup'
  ) => {
    const imageToRefine = imageFiles.find(img => img.id === imageId);
    if (!imageToRefine) return;

    setRefinementState(prev => ({ ...prev, [imageId]: true }));
    setError(null);

    let refinementPrompt = '';
    switch (refinementType) {
      case 'remove-background':
        refinementPrompt = 'Isolate the main product from this image and make the background transparent. Return a PNG image with an alpha channel.';
        break;
      case 'enhance':
        refinementPrompt = 'Professionally retouch this product photo. Enhance the lighting and color to make it look high-quality and vibrant, without changing the product itself.';
        break;
      case 'cleanup':
        refinementPrompt = 'Subtly clean up this product image. Remove any small dust particles, scratches, or minor imperfections on the product and its immediate surroundings. Keep the changes natural.';
        break;
    }

    try {
      const refinedImageBase64 = await refineImage(imageToRefine.file, refinementPrompt);
      const newFile = await base64ToFile(
        `data:image/png;base64,${refinedImageBase64}`, 
        `refined_${imageToRefine.file.name}`, 
        'image/png'
      );
      
      URL.revokeObjectURL(imageToRefine.preview);

      const newImageFile: ImageFile = {
        id: imageToRefine.id,
        file: newFile,
        preview: URL.createObjectURL(newFile),
      };

      setImageFiles(currentFiles =>
        currentFiles.map(file => (file.id === imageId ? newImageFile : file))
      );
    } catch (e) {
      console.error(e);
      setError('فشل تحسين الصورة. قد لا يتمكن النموذج من معالجة الطلب أو أن مفتاح API غير صالح.');
    } finally {
      setRefinementState(prev => ({ ...prev, [imageId]: false }));
    }
  }, [imageFiles]);

  const handleGenerateDescription = useCallback(async () => {
    if (imageFiles.length === 0) {
      setError('يرجى رفع صورة أولاً لإنشاء وصف.');
      return;
    }
    setError(null);
    setIsGeneratingDescription(true);
    try {
      const description = await generateDescriptionForImage(imageFiles[0].file);
      setPrompt(description);
    } catch (e) {
      console.error(e);
      setError('فشل في إنشاء الوصف. تأكد من صلاحية مفتاح API أو حاول مرة أخرى.');
    } finally {
      setIsGeneratingDescription(false);
    }
  }, [imageFiles]);

  const handleSubmit = useCallback(async () => {
    if (imageFiles.length === 0) {
      setError('يرجى رفع صورة منتج واحدة على الأقل.');
      return;
    }
    if (!prompt.trim()) {
      setError('يرجى تقديم وصف للمشهد النهائي.');
      return;
    }
    setError(null);
    setIsLoading(true);
    setGeneratedImage(null);
    setEditHistory([]);
    setHistoryIndex(-1);
    setVariationImages([]);
    try {
      const files = imageFiles.map(img => img.file);
      const newImage = await generateProductImage(files, prompt);
      const imageUrl = `data:image/jpeg;base64,${newImage}`;
      setGeneratedImage(imageUrl);
      setEditHistory([imageUrl]);
      setHistoryIndex(0);
    } catch (e) {
      console.error(e);
      setError('فشل في إنشاء الصورة. قد لا يتمكن النموذج من معالجة الطلب. يرجى تجربة وصف أو صور مختلفة، أو التأكد من صلاحية مفتاح API الخاص بك.');
    } finally {
      setIsLoading(false);
    }
  }, [imageFiles, prompt]);
  
  const handleGenerateHQ = useCallback(async () => {
    const currentImage = generatedImage;
    if (!currentImage) {
      setError('يجب إنشاء صورة أولاً قبل طلب جودة فائقة.');
      return;
    }
    setError(null);
    setIsLoading(true);
    setVariationImages([]);

    const hqPrompt = `أعد إنشاء هذه الصورة بجودة فائقة، واقعية جداً، بتركيز حاد، دقة 8k، كتصوير احترافي. حافظ على نفس المنتج والموضوع الأساسي.`;

    try {
      const imageFile = await base64ToFile(currentImage, 'hq-source.jpeg', 'image/jpeg');
      const newImageBase64 = await refineImage(imageFile, hqPrompt);
      const imageUrl = `data:image/jpeg;base64,${newImageBase64}`;
      
      const newHistory = editHistory.slice(0, historyIndex + 1);
      newHistory.push(imageUrl);
      setEditHistory(newHistory);
      setHistoryIndex(newHistory.length - 1);
      setGeneratedImage(imageUrl);
    } catch (e) {
      console.error(e);
      setError('فشل في تحسين الصورة. يرجى المحاولة مرة أخرى أو التأكد من صلاحية مفتاح API.');
    } finally {
      setIsLoading(false);
    }
  }, [generatedImage, editHistory, historyIndex]);

  const handlePostGenerationEdit = useCallback(async (editPrompt: string) => {
    const currentImage = editHistory[historyIndex];
    if (!currentImage) {
      setError('لا توجد صورة لتعديلها.');
      return;
    }
    setError(null);
    setIsEditing(true);

    try {
      const imageFile = await base64ToFile(currentImage, 'generated-image.jpeg', 'image/jpeg');
      const editedImageBase64 = await refineImage(imageFile, editPrompt);
      const newImageUrl = `data:image/jpeg;base64,${editedImageBase64}`;
      
      const newHistory = editHistory.slice(0, historyIndex + 1);
      newHistory.push(newImageUrl);

      setEditHistory(newHistory);
      setHistoryIndex(newHistory.length - 1);
      setGeneratedImage(newImageUrl);

    } catch (e) {
      console.error(e);
      setError('فشل تعديل الصورة. يرجى المحاولة مرة أخرى أو التأكد من صلاحية مفتاح API.');
    } finally {
      setIsEditing(false);
    }
  }, [editHistory, historyIndex]);
  
  const handleUndo = () => {
    if (historyIndex > 0) {
      const newIndex = historyIndex - 1;
      setHistoryIndex(newIndex);
      setGeneratedImage(editHistory[newIndex]);
    }
  };

  const handleRedo = () => {
    if (historyIndex < editHistory.length - 1) {
      const newIndex = historyIndex + 1;
      setHistoryIndex(newIndex);
      setGeneratedImage(editHistory[newIndex]);
    }
  };

  const handleGenerateVariations = useCallback(async () => {
    if (imageFiles.length === 0 || !prompt.trim()) {
      setError('لا يمكن إنشاء تنويعات بدون صور ووصف.');
      return;
    }
    setError(null);
    setIsGeneratingVariations(true);
    setVariationImages([]);
    try {
      const files = imageFiles.map(img => img.file);
      const variationPromises = Array(3).fill(null).map(() => generateProductImage(files, prompt));
      const results = await Promise.all(variationPromises);
      const variationUrls = results.map(base64 => `data:image/jpeg;base64,${base64}`);
      setVariationImages(variationUrls);
    } catch (e) {
      console.error(e);
      setError('فشل في إنشاء التنويعات. يرجى المحاولة مرة أخرى.');
    } finally {
      setIsGeneratingVariations(false);
    }
  }, [imageFiles, prompt]);

  const handleSelectVariation = (imageUrl: string) => {
    setGeneratedImage(imageUrl);
    setEditHistory([imageUrl]);
    setHistoryIndex(0);
    setVariationImages([]);
  };

  if (!isAuthenticated) {
    return <LoginComponent onLoginSuccess={handleLoginSuccess} />;
  }

  const mainActionLoading = isLoading || isGeneratingVariations;
  const getButtonText = () => {
      if (isLoading) return 'جاري إنشاء المشهد...';
      if (isGeneratingVariations) return 'جاري إنشاء التنويعات...';
      return '✨ إنشاء مشهد احترافي';
  }

  return (
    <div className={`min-h-screen bg-gray-900 text-gray-100 flex flex-col font-sans transition-opacity duration-500 ${appVisible ? 'opacity-100' : 'opacity-0'}`}>
      <Header onSettingsClick={() => setIsSettingsOpen(true)} />
      <SettingsModal isOpen={isSettingsOpen} onClose={handleSettingsClose} />
      <main className="flex-grow container mx-auto p-4 md:p-8 w-full">
        {apiKeyStatus && (
          <div className="mb-4 bg-blue-900/50 border border-blue-700 text-blue-300 px-4 py-2 rounded-lg text-xs text-center">
            أنت تستخدم حاليًا مفتاح API المخصص.
          </div>
        )}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
          <div className="flex flex-col gap-6 p-6 bg-gray-800/50 rounded-2xl shadow-lg border border-gray-700">
            <ImageUploader 
              onUpload={handleImageUpload} 
              maxFiles={5}
              imageFiles={imageFiles}
              onRefine={handleRefineImage}
              refinementState={refinementState}
            />
            <PromptControls
              prompt={prompt}
              setPrompt={setPrompt}
              onGenerateDescription={handleGenerateDescription}
              isGeneratingDescription={isGeneratingDescription}
              isImageUploaded={imageFiles.length > 0}
            />
            <StylePresets onSelect={(stylePrompt) => setPrompt(p => `${p.trim()} ${stylePrompt}`.trim())} />
            <BackgroundGallery onSelect={(bgPrompt) => setPrompt(p => `${bgPrompt}. ${p}`.trim())} />
            
            {error && (
              <div className="bg-red-900/50 border border-red-700 text-red-300 px-4 py-3 rounded-lg text-sm">
                {error}
              </div>
            )}
            <button
              onClick={handleSubmit}
              disabled={mainActionLoading || imageFiles.length === 0 || !prompt.trim()}
              className="w-full bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-900/50 disabled:cursor-not-allowed text-white font-bold py-3 px-4 rounded-lg transition-all duration-300 ease-in-out flex items-center justify-center text-lg shadow-indigo-500/30 shadow-md transform hover:scale-105"
            >
              {getButtonText()}
            </button>
          </div>
          <ResultDisplay
            isLoading={isLoading}
            generatedImage={generatedImage}
            onGenerateHQ={handleGenerateHQ}
            isEditing={isEditing}
            onEditImage={handlePostGenerationEdit}
            onUndo={handleUndo}
            onRedo={handleRedo}
            canUndo={historyIndex > 0}
            canRedo={historyIndex < editHistory.length - 1}
            isGeneratingVariations={isGeneratingVariations}
            variationImages={variationImages}
            onGenerateVariations={handleGenerateVariations}
            onSelectVariation={handleSelectVariation}
          />
        </div>
      </main>
      <Footer />
    </div>
  );
}

// --- RENDER APP ---
const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error("Could not find root element to mount to");
}

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);